# Generated by Django 3.1.4 on 2020-12-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201219_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('HOU', 'Housing'), ('TRA', 'Transportation'), ('FOO', 'Food & Groceries'), ('UTL', 'Utilities'), ('MED', 'Medical & Insurance'), ('SAV', 'Savings'), ('PER', 'Personal'), ('ENT', 'Entertainment'), ('EDU', 'Education'), ('GIF', 'Gifts & Donations')], default='FOO', max_length=3)),
                ('description', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.budget')),
            ],
        ),
    ]
